### ISSUE TITLE
Use `params` from rtk-query

### ISSUE THREAD

**Issue by DmitryScaletta** [Shiyan7/kinomore#8]
You can rewrite this code

https://github.com/Shiyan7/kinomore/blob/0b0cfc5335342634f309ff531e6d936ad67127bc/src/services/KinomoreService.ts#L13-L15

using `params` from rtk-query

```ts
getFilmById: build.query<IMovie, string | string[] | undefined>({ 
  query: id => {
    url: '/movie',
    params: {
      search: id,
      field: 'id',
      token: API_KEY,
    },
  },
}),
```

Documentation: https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery#setting-the-query-string

**Comment by Shiyan7** [comment]
апи так не умеет. search=sometext&field=someField - такой запрос повторяется много раз
